# Generated by Django 3.2.13 on 2022-05-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = []
